<!DOCTYPE html><html><div class="item-title">
        Item 104
      </div> <div class="item-details"><div><b>git_comments:</b> <ol></ol></div><div><b>git_commits:</b> <ol><li><div><div><b>summary:</b> CLOUDSTACK-4115 : Encrypt password in cluster_details table. This fix is to handle upgrades from versions earlier than 3.0.5 and 4.0. Upgrade was not handled when the cluster_details password encryption was introduced.
                </div><div><b>message:</b> CLOUDSTACK-4115 : Encrypt password in cluster_details table. This fix is to handle upgrades from versions earlier than 3.0.5 and 4.0. Upgrade was not handled when the cluster_details password encryption was introduced.

                </div></div></li></ol></div><div><b>github_issues:</b> <ol></ol></div><div><b>github_issues_comments:</b> <ol></ol></div><div><b>github_pulls:</b> <ol></ol></div><div><b>github_pulls_comments:</b> <ol></ol></div><div><b>github_pulls_reviews:</b> <ol></ol></div><div><b>jira_issues:</b> <ol><li><div><div><b>summary:</b> [upgrade][2.2.14 to 4.2]After upgrade the ESX 4.1 host ends up in disconnected state with EncryptionOperationNotPossibleException
                </div><div><b>description:</b> Steps :
================
1. Deploy a CS advanced zone setup with CS 2.2.14
2. Do some configurations.
3. upgrade to 4.2, then run cloudstack-setup-encryption and start management server

Expected behaviour:
===============
The upgrade should go through and the host should stay connected 

Observed behaviour :
===============
The host ends up in disconnected state after upgrade .

2013-08-06 21:37:01,972 DEBUG [agent.manager.ClusteredAgentManagerImpl] (ClusteredAgentManager Timer:null) Loading directly connected host 1(10.102.192.17)
2013-08-06 21:37:02,060 DEBUG [utils.crypt.DBEncryptionUtil] (ClusteredAgentManager Timer:null) Error while decrypting: freebsd*123
2013-08-06 21:37:02,061 DEBUG [cloud.host.Status] (ClusteredAgentManager Timer:null) Transition:[Resource state = Enabled, Agent event = AgentDisconnected, Host id = 1, name = 10.102.192.17]
2013-08-06 21:37:02,071 DEBUG [cloud.host.Status] (ClusteredAgentManager Timer:null) Agent status update: [id = 1; name = 10.102.192.17; old status = Disconnected; event = AgentDisconnected; new status = Disconnected; old update count = 4; new update count = 5]
2013-08-06 21:37:02,071 WARN  [agent.manager.ClusteredAgentManagerImpl] (ClusteredAgentManager Timer:null)  can not load directly connected host 1(10.102.192.17) due to
org.jasypt.exceptions.EncryptionOperationNotPossibleException
        at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.decrypt(StandardPBEByteEncryptor.java:918)
        at org.jasypt.encryption.pbe.StandardPBEStringEncryptor.decrypt(StandardPBEStringEncryptor.java:725)
        at com.cloud.utils.crypt.DBEncryptionUtil.decrypt(DBEncryptionUtil.java:65)
        at com.cloud.dc.ClusterDetailsDaoImpl.findDetails(ClusterDetailsDaoImpl.java:81)
        at com.cloud.utils.component.ComponentInstantiationPostProcessor$InterceptorDispatcher.intercept(ComponentInstantiationPostProcessor.java:125)
        at com.cloud.hypervisor.vmware.VmwareServerDiscoverer.buildConfigParams(VmwareServerDiscoverer.java:730)
        at com.cloud.hypervisor.vmware.VmwareServerDiscoverer.reloadResource(VmwareServerDiscoverer.java:760)
        at com.cloud.agent.manager.AgentManagerImpl.loadDirectlyConnectedHost(AgentManagerImpl.java:743)
        at com.cloud.agent.manager.ClusteredAgentManagerImpl.scanDirectAgentToLoad(ClusteredAgentManagerImpl.java:209)
        at com.cloud.agent.manager.ClusteredAgentManagerImpl.runDirectAgentScanTimerTask(ClusteredAgentManagerImpl.java:175)
        at com.cloud.agent.manager.ClusteredAgentManagerImpl.access$100(ClusteredAgentManagerImpl.java:93)
        at com.cloud.agent.manager.ClusteredAgentManagerImpl$DirectAgentScanTimerTask.run(ClusteredAgentManagerImpl.java:225)
        at java.util.TimerThread.mainLoop(Timer.java:534)
        at java.util.TimerThread.run(Timer.java:484)

                </div></div></li></ol></div><div><b>jira_issues_comments:</b> <ol><li><div>
                Attaching logs and dumps
              </div></li><li><div>
                Following is the workaround:
In cluster_details table value column is encrypted when name is password in an earlier release but upgrade code to encrypt the existing entries was missed. As result DB might have few values in plain text.

The solution is to replace that plain text password with an encrypted equivalent.

1. Encrypt the password for the vCenter account used by CloudStack and make note of the resulting ciphertext:
java -classpath /usr/share/java/cloud-jasypt-1.8.jar org.jasypt.intf.cli.JasyptPBEStringEncryptionCLI encrypt.sh input="_your_vCenter_password_" password="`cat /etc/cloud/management/key`" verbose=false
2. Back up the database:
mysqldump -u root -p cloud &gt; cloud_backup.sql
3. Find the id of the correct row of cluster_details to update... i.e. the row with the plain text password:
select * from cluster_details;
4. Update the plain text password with the encrypted one (be very careful to update the correct row):
update cluster_details set value = '_ciphertext_from_step_1_' where id = _id_from_step_3_;
5. Check the table again to confirm it looks good:
select * from cluster_details;

Once that is done, try adding the host again.
              </div></li><li><div>
                okay, i will try the workaround. But why did this happen? mine was a fresh setup so this shouldn't have happened. What if it happens again?
              </div></li><li><div><div><b>body:</b> Re-opening the issue, because after trying the workaround, the host came to "up" state but the creation of system vms is failing with :

13-08-07 19:54:47,236 DEBUG [cloud.network.NetworkManagerImpl] (secstorage-1:null) Asking BareMetalDhcp to prepare for Nic[119-40-null-10.102.195.67]
2013-08-07 19:54:47,236 DEBUG [cloud.network.NetworkManagerImpl] (secstorage-1:null) Asking BareMetalPxe to prepare for Nic[119-40-null-10.102.195.67]
2013-08-07 19:54:47,236 DEBUG [cloud.network.NetworkManagerImpl] (secstorage-1:null) Asking BareMetalUserdata to prepare for Nic[119-40-null-10.102.195.67]
2013-08-07 19:54:47,239 DEBUG [cloud.network.NetworkManagerImpl] (secstorage-1:null) Lock is acquired for network id 202 as a part of network implement
2013-08-07 19:54:47,240 DEBUG [cloud.network.NetworkManagerImpl] (secstorage-1:null) Network id=202 is already implemented
2013-08-07 19:54:47,241 DEBUG [cloud.network.NetworkManagerImpl] (secstorage-1:null) Lock is released for network id 202 as a part of network implement
2013-08-07 19:54:47,319 WARN  [vmware.resource.VmwareResource] (DirectAgent-16:10.102.192.17) StartCommand failed due to Exception: com.vmware.vim25.InvalidProperty
message: []

com.vmware.vim25.InvalidPropertyFaultMsg:
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:532)
        at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:130)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:108)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:78)
        at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:107)
        at sun.proxy.$Proxy89.retrieveProperties(Unknown Source)
        at com.cloud.hypervisor.vmware.util.VmwareClient.retrieveMoRefProperties(VmwareClient.java:263)
        at com.cloud.hypervisor.vmware.util.VmwareClient.getDynamicProperty(VmwareClient.java:218)
        at com.cloud.hypervisor.vmware.mo.VirtualMachineMO.getCoresPerSocket(VirtualMachineMO.java:2201)
        at com.cloud.hypervisor.vmware.mo.VirtualMachineMO.isCpuHotAddSupported(VirtualMachineMO.java:2242)
        at com.cloud.hypervisor.vmware.resource.VmwareResource.execute(VmwareResource.java:2674)
        at com.cloud.hypervisor.vmware.resource.VmwareResource.executeRequest(VmwareResource.java:518)
        at com.cloud.agent.manager.DirectAgentAttache$Task.run(DirectAgentAttache.java:186)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:165)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:679)
2013-08-07 19:54:47,323 DEBUG [agent.manager.DirectAgentAttache] (DirectAgent-16:null) Seq 1-609353762: Cancelling because one of the answers is false and it is stop on error.
2013-08-07 19:54:47,323 DEBUG [agent.manager.DirectAgentAttache] (DirectAgent-16:null) Seq 1-609353762: Response Received:
2013-08-07 19:54:47,327 DEBUG [agent.transport.Request] (DirectAgent-16:null) Seq 1-609353762: Processing:  { Ans: , MgmtId: 90310994128556, via: 1, Ver: v1, Flags: 10, [{"com.cloud.agent.api.StartAnswer":{"vm":{"id":36,"name":"v-36-VM","bootloader":"HVM","type":"ConsoleProxy","cpus":1,"minSpeed":500,"maxSpeed":500,"minRam":1073741824,"maxRam":1073741824,"arch":"i686","os":"Debian GNU/Linux 5.0 (32-bit)","bootArgs":" template=domP type=consoleproxy host=10.102.192.175 port=8250 name=v-36-VM premium=true zone=1 pod=1 guid=Proxy.36 proxy_vm=36 disable_rp_filter=true eth2ip=10.102.195.68 eth2mask=255.255.252.0 gateway=10.102.192.1 eth0ip=0.0.0.0 eth0mask=0.0.0.0 eth1ip=10.102.195.56 eth1mask=255.255.252.0 mgmtcidr=10.102.192.0/22 localgw=10.102.192.1 internaldns1=10.103.128.15 dns1=10.103.128.15","rebootOnCrash":false,"enableHA":false,"limitCpuUse":false,"enableDynamicallyScaleVm":false,"vncPassword":"36bb8d79846425d2","params":{"nicAdapter":"E1000"},"uuid":"f1e12329-f08c-42b8-ab39-fdd011b504d7","disks":[{"data":{"org.apache.cloudstack.storage.to.VolumeObjectTO":{"uuid":"cc465a2b-2a4c-4dcd-92f6-45fd7b6e6dcb","volumeType":"ROOT","dataStore":{"org.apache.cloudstack.storage.to.PrimaryDataStoreTO":{"uuid":"3f4c460a-1634-3db0-8b1f-60fe7b17a264","id":202,"poolType":"NetworkFilesystem","host":"10.102.192.100","path":"/cpg_vol/abhinav/esx-pri2","port":2049}},"name":"ROOT-36","size":2097152000,"path":"ROOT-36","volumeId":39,"vmName":"v-36-VM","accountId":1,"format":"OVA","id":39,"hypervisorType":"VMware"}},"diskSeq":0,"type":"ROOT"}],"nics":[{"deviceId":2,"networkRateMbps":-1,"defaultNic":true,"uuid":"7d688a60-4531-4be6-a81a-1fae6951763a","ip":"10.102.195.68","netmask":"255.255.252.0","gateway":"10.102.192.1","mac":"06:50:9a:00:00:12","dns1":"10.103.128.15","broadcastType":"Vlan","type":"Public","broadcastUri":"vlan://untagged","isolationUri":"vlan://untagged","isSecurityGroupEnabled":false},{"deviceId":0,"networkRateMbps":-1,"defaultNic":false,"uuid":"07027cf2-afb1-420c-b4e1-24da7973eee3","mac":"02:00:17:e7:00:1e","broadcastType":"LinkLocal","type":"Control","isSecurityGroupEnabled":false},{"deviceId":1,"networkRateMbps":-1,"defaultNic":false,"uuid":"fd495339-45ad-4f5a-8e49-2fcc5836d3d0","ip":"10.102.195.56","netmask":"255.255.252.0","gateway":"10.102.192.1","mac":"06:14:42:00:00:06","broadcastType":"Native","type":"Management","isSecurityGroupEnabled":false}]},"result":false,"details":"StartCommand failed due to Exception: com.vmware.vim25.InvalidProperty\nmessage: []\n","wait":0}}] }
2013-08-07 19:54:47,327 DEBUG [agent.transport.Request] (consoleproxy-1:null) Seq 1-609353762: Received:  { Ans: , MgmtId: 90310994128556, via: 1, Ver: v1, Flags: 10, { StartAnswer } }
2013-08-07 19:54:47,329 INFO  [cloud.vm.VirtualMachineManagerImpl] (consoleproxy-1:null) Unable to start VM on Host[-1-Routing] due to StartCommand failed due to Exception: com.vmware.vim25.InvalidProperty
message: []


                </div><div><b>label:</b> code-design
                </div></div></li><li><div>
                attaching management server log and DB dump
              </div></li><li><div>
                As per the bug description it was an upgrade from 2.2.14 and not fresh setup.
              </div></li><li><div>
                yes Kishan, it was upgrade but on VMs and host which were freshly installed. They were not the used vms and hosts.
              </div></li><li><div>
                Below error is not related to encryption.  "StartCommand failed due to Exception: com.vmware.vim25.InvalidProperty 
message: "

It could be related to CLOUDSTACK-2316. Can you please open a separate bug for this.
              </div></li><li><div>
                Opened a Doc. bug for the original issue of disconnected host at 
https://issues.apache.org/jira/browse/CLOUDSTACK-4185

A bug for the system vms not coming up at 
https://issues.apache.org/jira/browse/CLOUDSTACK-4181

So, closing this bug
              </div></li><li><div>
                Is this defect applicable only if use install.sh script ? Please confirm
              </div></li><li><div>
                This is applicable if there any Vmware cluster prior to upgrade. It is not related to install.sh script
              </div></li><li><div><div><b>body:</b> Reopening to avoid workaround for upgrades from versions earlier than 3.0.5 and 4.0
                </div><div><b>label:</b> code-design
                </div></div></li><li><div>
                Commit ad0fba31a31c4b56332d8223ba4a781c059914e0 in branch refs/heads/master from [~kishan]
[ https://git-wip-us.apache.org/repos/asf?p=cloudstack.git;h=ad0fba3 ]

CLOUDSTACK-4115 : Encrypt password in cluster_details table. This fix is to handle upgrades from versions earlier than 3.0.5 and 4.0. Upgrade was not handled when the cluster_details password encryption was introduced.

              </div></li><li><div>
                Commit bbe8a6d266cd9aff659b697ea1fcbc36ec854f5a in branch refs/heads/4.2-forward from [~kishan]
[ https://git-wip-us.apache.org/repos/asf?p=cloudstack.git;h=bbe8a6d ]

CLOUDSTACK-4115 : Encrypt password in cluster_details table. This fix is to handle upgrades from versions earlier than 3.0.5 and 4.0. Upgrade was not handled when the cluster_details password encryption was introduced.

              </div></li><li><div>
                See commits to this bug. Should this bug be resolved now?
              </div></li><li><div>
                I will cherry-pick the patch into 4.2 and the resolve the issue
              </div></li><li><div>
                Commit 5b4e5935a58fd3047a1c475292824b566a415b87 in branch refs/heads/4.2 from [~kishan]
[ https://git-wip-us.apache.org/repos/asf?p=cloudstack.git;h=5b4e593 ]

CLOUDSTACK-4115 : Encrypt password in cluster_details table. This fix is to handle upgrades from versions earlier than 3.0.5 and 4.0. Upgrade was not handled when the cluster_details password encryption was introduced.
(cherry picked from commit bbe8a6d266cd9aff659b697ea1fcbc36ec854f5a)

Signed-off-by: animesh &lt;animesh@apache.org&gt;

              </div></li><li><div>
                validated the fix
              </div></li></ol></div></div></html>