<!DOCTYPE html><html><div class="item-title">
        Item 238
      </div> <div class="item-details"><div><b>git_comments:</b> <ol></ol></div><div><b>git_commits:</b> <ol><li><div><div><b>summary:</b> IGNITE-4767: rollback exception hides the origin exception (e.g. commit): Suppressing or logging rollback exceptions instead of hiding the origin exception
                </div><div><b>message:</b> IGNITE-4767: rollback exception hides the origin exception (e.g. commit): Suppressing or logging rollback exceptions instead of hiding the origin exception
Fixes #1599

                </div></div></li></ol></div><div><b>github_issues:</b> <ol></ol></div><div><b>github_issues_comments:</b> <ol></ol></div><div><b>github_pulls:</b> <ol><li><div><div><b>title:</b> ignite-4767
                </div><div><b>body:</b> Suppressing or logging rollback exceptions instead of hiding the origin exception
                </div><div><b>label:</b> code-design
                </div></div></li><li><div><div><b>title:</b> ignite-4767
                </div><div><b>body:</b> Suppressing or logging rollback exceptions instead of hiding the origin exception
                </div></div></li></ol></div><div><b>github_pulls_comments:</b> <ol></ol></div><div><b>github_pulls_reviews:</b> <ol></ol></div><div><b>jira_issues:</b> <ol><li><div><div><b>summary:</b> rollback exception hides the origin exception (e.g. commit)
                </div><div><b>description:</b> There is too much code places like:
{noformat}
try {
	return txFuture.get();
}
catch (IgniteCheckedException e) {
	tx.rollbackAsync();

	throw e;
}
{noformat}
where an error upon rollback hides the actual exception {{e}}.

This should be implemented in the way like try-with-resources does:
{noformat}
try {
	return txFuture.get();
}
catch (IgniteCheckedException e1) {
	try {
		tx.rollbackAsync();
	}
	catch (Throwable inner) {
		e.addSuppressed(inner);
	}

	throw e;
}
{noformat}

                </div></div></li></ol></div><div><b>jira_issues_comments:</b> <ol><li><div>
                Testing done, please review
https://github.com/apache/ignite/pull/1599/files
              </div></li><li><div>
                Hi, [~ein],

I've checked the change and it seems to be OK.
In the same time e.getSuppressed() is never called. Is it indended to be logged into apache log throught printStackTrace. Is suppressed exception logged automatically or any additional change is required?

One more question, could you please share the link to TC run? Was it in Ignite20Tests?

              </div></li><li><div>
                Hi, [~dpavlov],

Suppressed exceptions will be automatically logged when stack trace is printed. Actually we should not worry about it.

I've found only this TC run in history, related to the 1599 PR
http://195.239.208.174/viewType.html?buildTypeId=IgniteTests_IgniteCache3&amp;tab=buildTypeStatusDiv&amp;branch_IgniteTests=pull%2F1599%2Fhead

Testing was done 2 months ago after merging with the master, I think Ignite20Tests was not present at that time.
              </div></li><li><div>
                I've restarted tests for 2.0 group using RunAll chain: 
http://ci.ignite.apache.org/project.html?projectId=Ignite20Tests&amp;branch_Ignite20Tests=pull%2F1599%2Fhead
              </div></li><li><div>
                Merged to master
              </div></li></ol></div></div></html>