<!DOCTYPE html><html><div class="item-title">
        Item 310
      </div> <div class="item-details"><div><b>git_comments:</b> <ol><li><div>
                 a dummy call just to test if the API works for merge_batches=True
              </div></li></ol></div><div><b>git_commits:</b> <ol><li><div><div><b>summary:</b> Merge pull request #1989 from pluskid/master
                </div><div><b>message:</b> Merge pull request #1989 from pluskid/master

Fix module.predict
                </div></div></li></ol></div><div><b>github_issues:</b> <ol><li><div><div><b>title:</b> mxnet.ndarray.NDArray objects cannot be concatenated
                </div><div><b>body:</b> I had some problems after converting my network from `mxnet.model.FeedForward` to `mxnet.module.Module` when using the `predict()` method.

With a module that has been trained, and a DataIterator `test_iter`, the following returns an error:

``` python
mod.predict(test_iter)
```

The exception raised is:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
&lt;ipython-input-134-73b4dc77d8cf&gt; in &lt;module&gt;()
----&gt; 1 model.predict(test_iter)

python/mxnet/module/base_module.py in predict(self, eval_data, num_batch, merge_batches, reset, always_output_list)
    259                        'in mini-batches. Maybe bucketing is used?'
    260             output_list2 = [np.concatenate([out[i] for out in output_list])
--&gt; 261                             for i in range(num_outputs)]

ValueError: zero-dimensional arrays cannot be concatenated
```

[The code in question appears here](https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/base_module.py#L260)

The problem seems to be due to trying to concatenate `mxnet.ndarray.NDArray` objects, which appear to have dimension 0.

``` python
&gt;&gt;&gt; pred = model.predict(test_iter, merge_batches=False) # This works 
&gt;&gt;&gt; np.ndim(pred[0][0]) 
0
# Checking that it's not due to end-of-batch-effects
&gt;&gt;&gt; len(pred)
79
&gt;&gt;&gt; pred[0]
[&lt;mxnet.ndarray.NDArray at 0x1269f9240&gt;]
&gt;&gt;&gt; np.concatenate([pred[0][0], pred[1][0]]) 
...
ValueError: zero-dimensional arrays cannot be concatenated
```

There is no problem when using `mxnet.model.FeedForward.predict()`, so I took a look to see what was different between the two `predict()` functions. 

In the `FeedForward` one, outputs are converted to numpy arrays before concatenation, which solves the problem pretty easily.

[`mxnet.model.FeedForward.predict`](https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L619)

I will attach a minor change in lieu of rewriting the NDArray module to support concatenation. 

                </div></div></li><li><div><div><b>title:</b> mxnet.ndarray.NDArray objects cannot be concatenated
                </div><div><b>body:</b> I had some problems after converting my network from `mxnet.model.FeedForward` to `mxnet.module.Module` when using the `predict()` method.

With a module that has been trained, and a DataIterator `test_iter`, the following returns an error:

``` python
mod.predict(test_iter)
```

The exception raised is:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
&lt;ipython-input-134-73b4dc77d8cf&gt; in &lt;module&gt;()
----&gt; 1 model.predict(test_iter)

python/mxnet/module/base_module.py in predict(self, eval_data, num_batch, merge_batches, reset, always_output_list)
    259                        'in mini-batches. Maybe bucketing is used?'
    260             output_list2 = [np.concatenate([out[i] for out in output_list])
--&gt; 261                             for i in range(num_outputs)]

ValueError: zero-dimensional arrays cannot be concatenated
```

[The code in question appears here](https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/base_module.py#L260)

The problem seems to be due to trying to concatenate `mxnet.ndarray.NDArray` objects, which appear to have dimension 0.

``` python
&gt;&gt;&gt; pred = model.predict(test_iter, merge_batches=False) # This works 
&gt;&gt;&gt; np.ndim(pred[0][0]) 
0
# Checking that it's not due to end-of-batch-effects
&gt;&gt;&gt; len(pred)
79
&gt;&gt;&gt; pred[0]
[&lt;mxnet.ndarray.NDArray at 0x1269f9240&gt;]
&gt;&gt;&gt; np.concatenate([pred[0][0], pred[1][0]]) 
...
ValueError: zero-dimensional arrays cannot be concatenated
```

There is no problem when using `mxnet.model.FeedForward.predict()`, so I took a look to see what was different between the two `predict()` functions. 

In the `FeedForward` one, outputs are converted to numpy arrays before concatenation, which solves the problem pretty easily.

[`mxnet.model.FeedForward.predict`](https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L619)

I will attach a minor change in lieu of rewriting the NDArray module to support concatenation. 

                </div><div><b>label:</b> code-design
                </div></div></li><li><div><div><b>title:</b> mxnet.ndarray.NDArray objects cannot be concatenated
                </div><div><b>body:</b> I had some problems after converting my network from `mxnet.model.FeedForward` to `mxnet.module.Module` when using the `predict()` method.

With a module that has been trained, and a DataIterator `test_iter`, the following returns an error:

``` python
mod.predict(test_iter)
```

The exception raised is:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
&lt;ipython-input-134-73b4dc77d8cf&gt; in &lt;module&gt;()
----&gt; 1 model.predict(test_iter)

python/mxnet/module/base_module.py in predict(self, eval_data, num_batch, merge_batches, reset, always_output_list)
    259                        'in mini-batches. Maybe bucketing is used?'
    260             output_list2 = [np.concatenate([out[i] for out in output_list])
--&gt; 261                             for i in range(num_outputs)]

ValueError: zero-dimensional arrays cannot be concatenated
```

[The code in question appears here](https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/base_module.py#L260)

The problem seems to be due to trying to concatenate `mxnet.ndarray.NDArray` objects, which appear to have dimension 0.

``` python
&gt;&gt;&gt; pred = model.predict(test_iter, merge_batches=False) # This works 
&gt;&gt;&gt; np.ndim(pred[0][0]) 
0
# Checking that it's not due to end-of-batch-effects
&gt;&gt;&gt; len(pred)
79
&gt;&gt;&gt; pred[0]
[&lt;mxnet.ndarray.NDArray at 0x1269f9240&gt;]
&gt;&gt;&gt; np.concatenate([pred[0][0], pred[1][0]]) 
...
ValueError: zero-dimensional arrays cannot be concatenated
```

There is no problem when using `mxnet.model.FeedForward.predict()`, so I took a look to see what was different between the two `predict()` functions. 

In the `FeedForward` one, outputs are converted to numpy arrays before concatenation, which solves the problem pretty easily.

[`mxnet.model.FeedForward.predict`](https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L619)

I will attach a minor change in lieu of rewriting the NDArray module to support concatenation. 

                </div></div></li><li><div><div><b>title:</b> mxnet.ndarray.NDArray objects cannot be concatenated
                </div><div><b>body:</b> I had some problems after converting my network from `mxnet.model.FeedForward` to `mxnet.module.Module` when using the `predict()` method.

With a module that has been trained, and a DataIterator `test_iter`, the following returns an error:

``` python
mod.predict(test_iter)
```

The exception raised is:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
&lt;ipython-input-134-73b4dc77d8cf&gt; in &lt;module&gt;()
----&gt; 1 model.predict(test_iter)

python/mxnet/module/base_module.py in predict(self, eval_data, num_batch, merge_batches, reset, always_output_list)
    259                        'in mini-batches. Maybe bucketing is used?'
    260             output_list2 = [np.concatenate([out[i] for out in output_list])
--&gt; 261                             for i in range(num_outputs)]

ValueError: zero-dimensional arrays cannot be concatenated
```

[The code in question appears here](https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/base_module.py#L260)

The problem seems to be due to trying to concatenate `mxnet.ndarray.NDArray` objects, which appear to have dimension 0.

``` python
&gt;&gt;&gt; pred = model.predict(test_iter, merge_batches=False) # This works 
&gt;&gt;&gt; np.ndim(pred[0][0]) 
0
# Checking that it's not due to end-of-batch-effects
&gt;&gt;&gt; len(pred)
79
&gt;&gt;&gt; pred[0]
[&lt;mxnet.ndarray.NDArray at 0x1269f9240&gt;]
&gt;&gt;&gt; np.concatenate([pred[0][0], pred[1][0]]) 
...
ValueError: zero-dimensional arrays cannot be concatenated
```

There is no problem when using `mxnet.model.FeedForward.predict()`, so I took a look to see what was different between the two `predict()` functions. 

In the `FeedForward` one, outputs are converted to numpy arrays before concatenation, which solves the problem pretty easily.

[`mxnet.model.FeedForward.predict`](https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L619)

I will attach a minor change in lieu of rewriting the NDArray module to support concatenation. 

                </div></div></li><li><div><div><b>title:</b> mxnet.ndarray.NDArray objects cannot be concatenated
                </div><div><b>body:</b> I had some problems after converting my network from `mxnet.model.FeedForward` to `mxnet.module.Module` when using the `predict()` method.

With a module that has been trained, and a DataIterator `test_iter`, the following returns an error:

``` python
mod.predict(test_iter)
```

The exception raised is:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
&lt;ipython-input-134-73b4dc77d8cf&gt; in &lt;module&gt;()
----&gt; 1 model.predict(test_iter)

python/mxnet/module/base_module.py in predict(self, eval_data, num_batch, merge_batches, reset, always_output_list)
    259                        'in mini-batches. Maybe bucketing is used?'
    260             output_list2 = [np.concatenate([out[i] for out in output_list])
--&gt; 261                             for i in range(num_outputs)]

ValueError: zero-dimensional arrays cannot be concatenated
```

[The code in question appears here](https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/base_module.py#L260)

The problem seems to be due to trying to concatenate `mxnet.ndarray.NDArray` objects, which appear to have dimension 0.

``` python
&gt;&gt;&gt; pred = model.predict(test_iter, merge_batches=False) # This works 
&gt;&gt;&gt; np.ndim(pred[0][0]) 
0
# Checking that it's not due to end-of-batch-effects
&gt;&gt;&gt; len(pred)
79
&gt;&gt;&gt; pred[0]
[&lt;mxnet.ndarray.NDArray at 0x1269f9240&gt;]
&gt;&gt;&gt; np.concatenate([pred[0][0], pred[1][0]]) 
...
ValueError: zero-dimensional arrays cannot be concatenated
```

There is no problem when using `mxnet.model.FeedForward.predict()`, so I took a look to see what was different between the two `predict()` functions. 

In the `FeedForward` one, outputs are converted to numpy arrays before concatenation, which solves the problem pretty easily.

[`mxnet.model.FeedForward.predict`](https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L619)

I will attach a minor change in lieu of rewriting the NDArray module to support concatenation. 

                </div></div></li></ol></div><div><b>github_issues_comments:</b> <ol><li><div>
                OK, I am unsure of how to get this to work since I already have a pull request pending, but there's some sort of issue with the linter so it hasn't been merged.
So now they appear to be two commits on the same pull request, #1977

The change I suggested was for `mxnet/python/mxnet/module/base_module.py`, altering line 247:

```
-            outputs = [out[0:out.shape[0]-pad] for out in self.get_outputs()]
+            outputs = [out[0:out.shape[0]-pad].asnumpy() for out in self.get_outputs()]
```

I can attest that it fixed my issues using `predict` and seemed like the easiest change that would ensure similar behavior.

              </div></li><li><div><div><b>body:</b> @rldotai Thanks for spotting this bug! I proposed a different fix in #1989, which still keeps the `NDArray` as output types, but call `nd.concatenate` instead of `np.concatenate`. Returning `NDArray` allows us to better utilize the asynchronized execution engine in the backend and also a relatively consistent API. Please call `asnumpy()` explicitly on the returned results if you need to work with numpy. Thanks again!

                </div><div><b>label:</b> code-design
                </div></div></li><li><div>
                No worries, just glad to help.

              </div></li></ol></div><div><b>github_pulls:</b> <ol><li><div><div><b>title:</b> Fix module.predict
                </div><div><b>body:</b> See #1985

Also changed `fit` to reset eval metric on training data for each batch, to be compatible with the recent changes in `FeedForward`.

                </div></div></li><li><div><div><b>title:</b> Fix module.predict
                </div><div><b>body:</b> See #1985

Also changed `fit` to reset eval metric on training data for each batch, to be compatible with the recent changes in `FeedForward`.

                </div></div></li><li><div><div><b>title:</b> Fix module.predict
                </div><div><b>body:</b> See #1985

Also changed `fit` to reset eval metric on training data for each batch, to be compatible with the recent changes in `FeedForward`.

                </div></div></li><li><div><div><b>title:</b> Fix module.predict
                </div><div><b>body:</b> See #1985

Also changed `fit` to reset eval metric on training data for each batch, to be compatible with the recent changes in `FeedForward`.

                </div></div></li><li><div><div><b>title:</b> Fix module.predict
                </div><div><b>body:</b> See #1985

Also changed `fit` to reset eval metric on training data for each batch, to be compatible with the recent changes in `FeedForward`.

                </div></div></li><li><div><div><b>title:</b> Fix module.predict
                </div><div><b>body:</b> See #1985

Also changed `fit` to reset eval metric on training data for each batch, to be compatible with the recent changes in `FeedForward`.

                </div><div><b>label:</b> code-design
                </div></div></li><li><div><div><b>title:</b> Fix module.predict
                </div><div><b>body:</b> See #1985

Also changed `fit` to reset eval metric on training data for each batch, to be compatible with the recent changes in `FeedForward`.

                </div></div></li><li><div><div><b>title:</b> Fix module.predict
                </div><div><b>body:</b> See #1985

Also changed `fit` to reset eval metric on training data for each batch, to be compatible with the recent changes in `FeedForward`.

                </div><div><b>label:</b> code-design
                </div></div></li><li><div><div><b>title:</b> Fix module.predict
                </div><div><b>body:</b> See #1985

Also changed `fit` to reset eval metric on training data for each batch, to be compatible with the recent changes in `FeedForward`.

                </div><div><b>label:</b> code-design
                </div></div></li><li><div><div><b>title:</b> Fix module.predict
                </div><div><b>body:</b> See #1985

Also changed `fit` to reset eval metric on training data for each batch, to be compatible with the recent changes in `FeedForward`.

                </div></div></li></ol></div><div><b>github_pulls_comments:</b> <ol><li><div>
                let me know if you think it is good to merge things in. the r test seems to be broken for unknown reasons @thirdwing can you look into if some of the testcase break because recent updates in dependent libraries?

              </div></li><li><div>
                Looks like you removed the metric reset. I meant it should be reset whenever you print metric. Is that what it's doing now?

Otherwise looks good to me

              </div></li><li><div>
                @piiswrong Yes, the validation on val set will reset the eval_metric. Otherwise, the eval_metric will also got reset at the beginning of each epoch.

@tqchen can you merge it? Thanks!

              </div></li></ol></div><div><b>github_pulls_reviews:</b> <ol><li><div>
                I think reset on each reporting is better

              </div></li><li><div><div><b>body:</b> I agree with this change but this is not backward compatible. Maybe add a option to output ndarray and set false as default?

                </div><div><b>label:</b> code-design
                </div></div></li><li><div>
                OK agreed.

              </div></li><li><div><div><b>body:</b> I think in this particular case it is better to keep a relatively unified interface than to keep it (exactly) backward compatible. Otherwise, it is also a question that whether you want to return np.array or ndarray for `iter_predict`. I think since the module API is already not exactly compatible with `FeedForward`, my personal opinion is to use this chance to have a cleaner interface here. I guess it might also perform better without those blocking `asnumpy()` call after each `forward`.

                </div><div><b>label:</b> code-design
                </div></div></li><li><div><div><b>body:</b> Ok I didn't notice this is for module. Then I guess it's ok since there isn't much legacy code depending on this

                </div><div><b>label:</b> code-design
                </div></div></li></ol></div><div><b>jira_issues:</b> <ol></ol></div><div><b>jira_issues_comments:</b> <ol></ol></div></div></html>